[2025-06-07T21:59:34.815-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: taxi_pipeline.train_model scheduled__2025-06-07T00:34:53.303328+00:00 [queued]>
[2025-06-07T21:59:34.820-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: taxi_pipeline.train_model scheduled__2025-06-07T00:34:53.303328+00:00 [queued]>
[2025-06-07T21:59:34.820-0300] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-06-07T21:59:34.940-0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): train_model> on 2025-06-07 00:34:53.303328+00:00
[2025-06-07T21:59:34.944-0300] {standard_task_runner.py:57} INFO - Started process 33485 to run task
[2025-06-07T21:59:34.946-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'taxi_pipeline', 'train_model', 'scheduled__2025-06-07T00:34:53.303328+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/taxi_dag.py', '--cfg-path', '/tmp/tmpea61lz82']
[2025-06-07T21:59:34.946-0300] {standard_task_runner.py:85} INFO - Job 82: Subtask train_model
[2025-06-07T21:59:35.174-0300] {task_command.py:410} INFO - Running <TaskInstance: taxi_pipeline.train_model scheduled__2025-06-07T00:34:53.303328+00:00 [running]> on host alex-MS-7D46
[2025-06-07T21:59:35.626-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='taxi_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T00:34:53.303328+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-07T00:34:53.303328+00:00'
[2025-06-07T22:00:13.162-0300] {logging_mixin.py:150} WARNING - 2025/06/07 22:00:13 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp4d00yrg1/model/model.pkl, flavor: sklearn). Fall back to return ['scikit-learn==1.4.0', 'cloudpickle==3.1.1']. Set logging level to DEBUG to see the full traceback.
[2025-06-07T22:00:13.167-0300] {logging_mixin.py:150} WARNING - 2025/06/07 22:00:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-07T22:00:13.345-0300] {logging_mixin.py:150} WARNING - Registered model 'MyLinearRegressor' already exists. Creating a new version of this model...
[2025-06-07T22:00:13.459-0300] {logging_mixin.py:150} WARNING - Created version '2' of model 'MyLinearRegressor'.
[2025-06-07T22:00:13.578-0300] {python.py:183} INFO - Done. Returned value was: None
[2025-06-07T22:00:13.589-0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=taxi_pipeline, task_id=train_model, execution_date=20250607T003453, start_date=20250608T005934, end_date=20250608T010013
[2025-06-07T22:00:13.791-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-07T22:00:13.807-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
